### ISSUE TITLE
PVPMicroButton -- unable to change the texture

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicWOTLK#10]
There is some UI code for this to probably change alliance/horde icon so its not simply possible to replace the button texture.

Needs investigating on where this is handled and how to disable it.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/184418779-cb202cbc-e1c9-4d93-a64a-271177faa575.png)

**Comment by Evolvee** [comment]
could possibly be fixed by replacing texture in TargetingFrame/UI-PVP-Alliance.blp and TargetingFrame/UI-PVP-Horde.blp ? might affect more elements of the UI tho (PVP tab etc,)

**Comment by Shanghi** [comment]
It looks like that icon is only set one time when loading so I just added a line to hide it and hopefully nothing will ever show it again!
