### ISSUE TITLE
Reputation UI tab is "bugged"

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicWOTLK#11]
![image](https://user-images.githubusercontent.com/1942409/183247106-d68abc13-10c1-408b-892a-ca0a73bdc02b.png)

weird black lines + the info panel is missing background textures

**Comment by Shanghi** [comment]
The UI-Character-ReputationBar.blp image is very different in wotlk!

![ui-character-reputationbar](https://user-images.githubusercontent.com/2672633/185123076-33cca3b2-342d-4b91-a3bd-15cf195fb6b2.png)

**Comment by Evolvee** [comment]
Alright I guess this will do it for now

![image](https://user-images.githubusercontent.com/1942409/185176851-7add9a57-44d4-4d16-b2e2-41ebcbc05bf4.png)

there is a slight visual issue with "hated" reputations --> the red texture isnt placed correctly --> i used the exported original blizzard art btw (I recolored the black part ) so this has to be Default UI issue as well..

I will check it again in future when I am about to do a full UI recolouring.
