### ISSUE TITLE
Combat Floating Text is sometimes randomly getting disabled - same issue on classicTBC

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicWOTLK#13]
![image](https://user-images.githubusercontent.com/1942409/183249849-15ebf200-8237-4df2-8335-b1a982ac375f.png)

LF a hackfix that would make sure its ALWAYS enabled.

**Comment by Evolvee** [comment]
hackfixed by forcing cvar on each login

**Comment by Evolvee** [comment]
Nope, something is seriously fucked up, even when the config is bruteforced by setting cvar in the addon, the combat floating text events arent showing up unless player manually disables it and enables again despite it being visible enabled in the UI settings...

**Comment by XyzKangUI** [comment]
I believe you have to use VARIABLES_LOADED event.

**Comment by Evolvee** [comment]
> Check this https://github.com/phanx-wow/PhanxUI/blob/master/CVars.lua

What exactly am I supposed to see?

**Comment by Evolvee** [comment]
https://www.reddit.com/r/classicwow/comments/xewoo1/has_there_been_a_fix_to_the_floating_combat_text/?utm_medium=android_app&utm_source=share

**Comment by Evolvee** [comment]
doesnt seem to happen anymore with the way how cvars are handled now
