### ISSUE TITLE
ToDo: Add a better graphic to "clock" cooldowns

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicWOTLK#14]
https://github.com/Evolvee/EvolvePWPUI-ClassicTBC/issues/22

^^ Weak Aura addon has this a toggle-able option ... might want to investigate how they do it so we can copy pasta it onto LoseControl/OmniCC timers

Currently:
![image](https://user-images.githubusercontent.com/1942409/183740570-d1f3401d-af62-4045-90e6-e75af0c84b0b.png)

there is no border

how weak aura can do it:
![image](https://user-images.githubusercontent.com/1942409/183740952-008a1cf8-1d7a-49a1-a28f-4c92d422dcf4.png)
(the golden line)

......

So the wanted outcome is something in between - add a distinguishable line but not overkill its thickness.

**Comment by XyzKangUI** [comment]
Cooldown/edge.blp is the golden line. SetDrawEdge is the function.
