### ISSUE TITLE
[Visual] LF a way to edit the "shadow" texture that is displayed on top of icons with cooldown counting down

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicWOTLK#15]
![image](https://user-images.githubusercontent.com/1942409/183742496-531ad137-2e36-41e7-8284-3d78e749d19c.png)
When this is enabled, the "golden" "edge" thingy that circles around the cooldown makes the border square

e.g.:
![image](https://user-images.githubusercontent.com/1942409/183742641-577edc3a-bed8-408f-aa05-b8dbad4d6366.png)

top right corner is square
bottom right corner is square
bottom left corner is square
top left corner still has the original icon shape --> when the golden "edge" thingy passes through, it changes to square though like this:
![image](https://user-images.githubusercontent.com/1942409/183742843-c5b7787d-8637-4ee7-a0b4-e26c24d06a56.png)

TODO: prevent this behavior, i want my icons the way i made them, square=bad

**Comment by Evolvee** [comment]
Another way of fixing it would be solving https://github.com/Evolvee/EvolvePWPUI-ClassicWOTLK/issues/14 so we can apply it to weak auras as well instead of using this "placeholder" solution

**Comment by Evolvee** [comment]
Turns out this is the case for all other addons as well - for example LoseControl so we will have to figure out if there is some texture we can simply replace/override.

**Comment by XyzKangUI** [comment]
The square overlay is actually the swipe not the edge. Addons use SetSwipeColor to regulate its alpha and SetSwipeTexture for another overlay, e.g. LoseControl portraits.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/191061892-7c795deb-46d0-4084-89c4-7fe30cf75dfb.png)

LoseControl round textures dont have this issue.
