### ISSUE TITLE
ToDo: Figure out a way to hide DK pet (the zombie) nameplate

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicWOTLK#17]
Aparently its name is generated randomly(?)... no way, there has to be a set amount of random names it chooses from (similar to warlocks), gonna get the full list i guess.

Another solution to this is to make all pet nameplates smaller compared to player nameplates to distinguish them and reduce the clutter on screen.

**Comment by Shanghi** [comment]
It's possible to hide pet nameplates based on any of the tests you can do when normally looking at a target! The first test would be if it's a player's pet, then the others depend on which ones you want to hide. Is it just the Death Knight's zombie or should all pets be hidden or maybe everything except a certain kind? `UnitCreatureFamily(unit)` shows "Ghoul" for the zombie and I think that's the only pet like that so at least that one should be able to be hidden!

**Comment by Evolvee** [comment]
I think just the DK´s zombie for now yeah. WoTLK has so many annoying nameplates that dont really matter. Imagine enha + DK arena... tons of totems, 4 pets, 2 players... uugghh 🤮

**Comment by Shanghi** [comment]
I just updated TextureScript to hopefully hide only them! It seems to work based on what I could test in Dalaran searching for death knights that had one, then going to summon a gargoyle to make sure it didn't hide that.
