### ISSUE TITLE
ToDo: Disable the healthbar under tooltip

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicWOTLK#28]
![image](https://user-images.githubusercontent.com/1942409/185107117-05d3acdf-0912-4cfe-a553-27a2c0ba1c96.png)

![image](https://user-images.githubusercontent.com/1942409/185107137-323cdab9-7799-4a9c-a6c5-9f6b2a4fe087.png)

Its useless, only takes space.

**Comment by Shanghi** [comment]
I added something near the end of TextureScript to hopefully always hide it!
