### ISSUE TITLE
ToDo: remove the new red/yellow textures from target/focus/party frames

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicWOTLK#31]
idk what it is, maybe some new aggro bullshit from blizzard, and it looks rly retarded, gonna have to remove it or idk

no idea how to reproduce, doesnt always happen

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/185473449-2aa72966-1e4c-4187-b8f3-0470c24959b5.png)

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/185696672-218f696a-484b-44eb-94a3-f6a8613fc6e8.png)

**Comment by XyzKangUI** [comment]
SetCVar("threatWarning", 0)

**Comment by Evolvee** [comment]
Thx
