### ISSUE TITLE
ToDo: Succubus seduce - need to add some weakaura super-warning for it or idk ... pets are not visible instantly upon leaving stealth so its impossible to see the cast

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicWOTLK#37]

**Comment by XyzKangUI** [comment]
The cast is 0.51s talented. When it does its first seduction leaving invis you can track SPELL_CAST_SUCCESS and then when its in combat SPELL_CAST_START becomes trackable.

**Comment by XyzKangUI** [comment]
First time when succubus casts Seduction it will only show the "SPELL_CAST_SUCCESS" event. After that when she is in combat and cannot re-enter invis it will be trackable with "SPELL_CAST_START". Other than that the cast is 0.51s talented.

**Comment by Evolvee** [comment]
The issue is mainly this https://github.com/JamminL/wotlk-classic-bugs/issues/333
^^ if this wasnt a problem I wouldnt have to figure out some obscure ways...

**Comment by XyzKangUI** [comment]
What a game :/
