### ISSUE TITLE
ToDo: Hide nameplates of hunter pets and mage pets/mirror images as well

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicWOTLK#38]
actually it might be better to just disable all pet nameplates in the default UI when im thinking about it and make exceptions that i want to see (sucubus for example)

**Comment by XyzKangUI** [comment]
https://github.com/XyzKangUI/RougeUI/blob/wotlk/Interface/AddOns/RougeUI/nameplate.lua#L60

This is the way I do it. If i'd want to hide water elemental then i'd need to add `npcID = "510" ` there. Hunter pets can be hidden by modifying the scripts `local npcType, _, _, _, _, npcId = str_split("-", UnitGUID(unit))` and then doing `if npcType == "Pet" `

Although to exclude succubus it would need to be `if npcType == "Pet" and not npcId == "1863"`

**Comment by Evolvee** [comment]
a new commit just came in (in this repo) for this issue, I will test the Pyralis implementation first, thanks for tip though!

**Comment by Evolvee** [comment]
Hmmm maybe not! Pyralis says your might be better :D

**Comment by Evolvee** [comment]
testing
