### ISSUE TITLE
Dalaran Arena has some bullshit "sewer" sounds shortly after the gate opens making all other spell sounds unhearable -- gotta remove that

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicWOTLK#39]
The "water is about to pure down" sound is causing this.

**Comment by Evolvee** [comment]
https://www.mmo-champion.com/threads/646486-Weird-sound-issues-in-RoV-and-Dalaran-Arena

**Comment by XyzKangUI** [comment]
I think I found the wind noise, but a weird thing in RoV the flames are using river sounds. Do you reckon that is a bug?

**Comment by XyzKangUI** [comment]
```
MuteSoundFile(598127) -- DalaranArena_WaterIncoming (event that water is incoming)
MuteSoundFile(565772) -- DalaranSewer_ArenaWaterFall_Closed
MuteSoundFile(569506) -- DalaranSewer_ArenaWaterFall_Close (dalaran arena mid water)

MuteSoundFile(598178) -- Orgrimmar_Arena_PillarWarning (event that pillar is coming)
MuteSoundFile(539024) -- CanyonDesertDay (RoV wind & Org/Valley wind birds)
MuteSoundFile(538974) -- Riverslow (RoV fire = water sound?)
MuteSoundFile(538973) -- Riverstill (RoV fire = water sound?)```

Do you have any idea which sound is the annoying continuous Dalaran sewers water stream?

**Comment by Evolvee** [comment]
565772 sounds like something you can loop

^^ thx for the others tho, gonna test it out

**Comment by Evolvee** [comment]
seems to work, the RoV fire is something else

**Comment by XyzKangUI** [comment]
Hm the rov fire works fine here, atleast I hear no more water sounds in RoV. Ive also muted the elevator. 

The only issue I have is the Dalaran sewers uninstanced flowing water "canals" / dalaran arena water from the pipe sound. I believe they are one and the same, just can't find out which.

**Comment by Evolvee** [comment]
You hear water sounds in RoV?:D maybe I am deaf or idk

Hmm yea, the water sound for instanced arena got eliminated, I dont mind the non-instanced one tho, its "calming" 😴

**Comment by XyzKangUI** [comment]
> You hear water sounds in RoV?:D maybe I am deaf or idk
> 
> Hmm yea, the water sound for instanced arena got eliminated, I dont mind the non-instanced one tho, its "calming" 😴
> 
> My main issue were these "massive" sound effects that lower all other sounds, especially spells.

I You hear the water sound after muting the wind when you are down the elevator. You also the water sound where the fire spawns. In this old video you can hear the wind and around 4-5s you hear water sounds https://youtu.be/7lIHcrXBeNA

Atm I just want to mute the water sound you hear in Dalaran Arena waiting room when you run close to the gates. Everytime I run past those corners in the arena i keep hearing that "waterfall" sound effect. Just can't find it. Also some files that are present in 3.3.5a client are missing from this one or their location changed :/

**Comment by Evolvee** [comment]
Hmm yea true, I didnt notice before. I think its a default sound though, not specifically related to dalaran arena only so you could mute half of the open world with it as well.

If you find it though let me know pls :D
