### ISSUE TITLE
ToDo: Remove Totem of Wrath debuff from self-debuff frame (if even possible)

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicWOTLK#40]
its completely useless, only takes space

**Comment by XyzKangUI** [comment]
It is possible: 

hooksecurefunc("AuraButton_Update", function(buttonName, index, filter)
	local _, _, _, _, _, _, _, _, _, spellId = UnitAura("player", index, filter);
	local buffName = buttonName..index;
	local buff = _G[buffName];

	if spellId == 30708 then buff:Hide() end
end)

**Comment by Evolvee** [comment]
Thanks! I will try it out.

**Comment by Evolvee** [comment]
> It is possible:
> 
> ```
> hooksecurefunc("AuraButton_Update", function(buttonName, index, filter)
> 	local _, _, _, _, _, _, _, _, _, spellId = UnitAura("player", index, filter);
> 	local buffName = buttonName..index;
> 	local buff = _G[buffName];
> 
> 	if spellId == 30708 then buff:Hide() end
> end)
> ```

There is an issue:
![image](https://user-images.githubusercontent.com/1942409/185789126-6bc7372b-446c-4fd7-9772-d7320ac8308e.png)

the debuff still takes space

**Comment by Evolvee** [comment]
There is an issue:
![image](https://user-images.githubusercontent.com/1942409/185789140-7f44ed37-d4f3-4d49-9b96-d1c93b008b0f.png)

the debuff still takes space

**Comment by Evolvee** [comment]
removing the script for now as its causing issues (leaving in a blanket space)
this issue is now part of https://github.com/Evolvee/EvolvePWPUI-ClassicWOTLK/issues/49
