### ISSUE TITLE
[Bug] ClassPortraits - fps lag spike when switching weapon + texture blinking/refreshing

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicWOTLK#51]
https://www.youtube.com/watch?v=ttcNHDRE41Y
https://youtu.be/gtLJc9wEuCk

**Comment by XyzKangUI** [comment]
Your method to use OnUpdate for class portrait is horrible. Either stick to using OnEvent with UNIT_PORTRAIT_UPDATE and PORTRAITS_UPDATED or use a simple hooksecurefunc that will replace half of your code

```
hooksecurefunc("UnitFramePortrait_Update",function(self)
	if self.unit == "player" then
		self.portrait:SetTexture("Interface\\Addons\\ClassPortraits\\MYSKIN")
		return
	elseif self.unit == "pet" then
		return
	end

	if self.portrait then
		if UnitIsPlayer(self.unit) then
			local t = CLASS_ICON_TCOORDS[select(2,UnitClass(self.unit))]
			if t then
				self.portrait:SetTexture(iconPath)
				self.portrait:SetTexCoord(unpack(t))
			end
		else
			self.portrait:SetTexCoord(0,1,0,1)
		end
	end
end);
```

**Comment by Evolvee** [comment]
I think this method is used in all the classportraits addons out there, but it was causing extreme fps issue on tbc beta - https://github.com/leatrix/leatrix-plus-wrath/issues/7 so I switched to the old 2.4.3 method I was using.

Perhaps blizzard already fixed their shit, will test it.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/188271749-9019119c-6ba4-4ce9-bb0b-e58ac2e247ef.png)

they didnt fix shit, unit portraits are refreshed every frame 24/7

**Comment by Evolvee** [comment]
it doesnt seem to cause as extreme fps issue as it did though, thx for suggestion, i will use it during the prepatch some more and test it against the last version

**Comment by XyzKangUI** [comment]
You were using OnUpdate, I don't see how that was any better by not having unit portraits being refreshed every frame 24/7. On top of your own OnUpdate there is another OnUpdate being used by Blizzard. Essentially `UnitFramePortrait_Update` is only called by two events, which is fine. 
The expensive part is that it is also being used in `UnitFrame_Update` which is invoked by `TargetFrame_OnUpdate` when a ToT is shown. With or without this hook you will have that spam you showed, simply because of Blizzard's code. 
The code itself to change portraits gets the blame because its hooked into the function, even an empty hook would report a high CPU usage in addons like "Addon Usage" and make you believe that this code is responsible for fps drops.

**Comment by XyzKangUI** [comment]
Actually looking at your old implementation I wonder if you ever tried just changing OnUpdate to OnEvent and registering 4 events: 
ClassPortraits:RegisterEvent("UNIT_PORTRAIT_UPDATE")
ClassPortraits:RegisterEvent("PORTRAITS_UPDATED")
ClassPortraits:RegisterEvent("PLAYER_TARGET_CHANGED")
ClassPortraits:RegisterEvent("PLAYER_FOCUS_CHANGED")

Wouldn't this be the best way for your class portraits. Probably even better than the hook.

**Comment by XyzKangUI** [comment]
Actually re-using your own code we can make the most efficient class portrait update hook.

This will only change player/target/focus portrait updates on actual events and the ToT once.

```
hooksecurefunc("UnitFramePortrait_Update", function(self)
	if self.unit == "player" then
		self.portrait:SetTexture("Interface\\Addons\\ClassPortraits\\MYSKIN")
		return
	elseif self.unit == "pet" then
		return
	end

	if self.portrait and not (self.unit == "targettarget" or self.unit == "focus-target") then
		if UnitIsPlayer(self.unit) then
			local t = CLASS_ICON_TCOORDS[select(2,UnitClass(self.unit))]
			if t then
				self.portrait:SetTexture(iconPath)
				self.portrait:SetTexCoord(unpack(t))
			end
		else
			self.portrait:SetTexCoord(0,1,0,1)
		end
	end

	if UnitExists("targettarget") ~= nil then
		if UnitGUID("targettarget") ~= lastTargetToTGuid then
			lastTargetToTGuid = UnitGUID("targettarget")
			if UnitIsPlayer("targettarget") then
				TargetToTPortrait:SetTexture(iconPath, true)
				local tt=classIcons[(select(2, UnitClass("targettarget")))]
				TargetToTPortrait:SetTexCoord(unpack(tt))
				TargetToTPortrait:Show()
			else
				TargetToTPortrait:Hide()
			end
		end
	else
		TargetToTPortrait:Hide()
		lastTargetToTGuid = nil
	end

	if UnitExists("focus-target") ~= nil then
		if UnitGUID("focus-target") ~= lastFocusToTGuid then
			lastFocusToTGuid = UnitGUID("focus-target")
			if UnitIsPlayer("focus-target") then
				FocusToTPortrait:SetTexture(iconPath, true)
				local tt=classIcons[(select(2, UnitClass("focus-target")))]
				FocusToTPortrait:SetTexCoord(unpack(tt))
				FocusToTPortrait:Show()
			else
				FocusToTPortrait:Hide()
			end
		end
	else
		FocusToTPortrait:Hide()
		lastFocusToTGuid = nil
	end
end)
```

**Comment by Evolvee** [comment]
Thanks! ToT is not that important for me, as im playing on a laptop, I value every bit of fps very much, especially due to 120hz monitor any drop below stable 120fps is very noticable.

On wotlk however, I noticed these drops occur even with no addons whatsoever, which wasnt rly happening with TBC that much, hopefully they will fix it _(Copium, we all know they wont fix shit)_

**Comment by XyzKangUI** [comment]
I also noticed during wotlk beta that my game would freeze sometimes, for example when i got an achievement. Luckily they fixed that, but I have no high hopes as well and will not even bother with wotlk. Btw im totally implementing that portrait code to my own addon 😄
