### ISSUE TITLE
plz help me hide nameplate level

### ISSUE THREAD

**Issue by pheeno** [Evolvee/EvolvePWPUI-ClassicWOTLK#75]
As title ,tell me how to hide level in nameplate, plz

**Comment by Evolvee** [comment]
You are using my UI or you want me to tell you how i achieved it? I dont understand...
For me the level isnt displayed properly so you are probably using some addon that fucks it up.

**Comment by Evolvee** [comment]
https://github.com/Evolvee/EvolvePWPUI-ClassicWOTLK/blob/main/Interface/AddOns/TextureScript/TextureScript.lua#L1548
this is why I hide the nameplate level
